INSERT INTO USERS
	(USER_NAME, FIRST_NAME, LAST_NAME, PASSWORD, CITY)
VALUES
	('severejetlag','Nick','Lee','password','San Francisco'),
	('darealmvp','Dan','lee','password','Boston'),
	('posts4days','Andy','lee','password','Denver'),
	('reddit4life','nick','lee','password','Syracuse'),
	('masterofposts','nick','lee','password','New Orleans');

INSERT INTO POSTS
    (TITLE, POST, USER_ID)
VALUES
    ('Test Post', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent feugiat convallis dui at maximus. Praesent quis justo mattis, dignissim arcu a, tincidunt nunc. Maecenas consectetur velit vitae sapien porta lacinia. Suspendisse bibendum metus sed dapibus mattis. Nunc consequat dictum dolor, eu vestibulum lorem. Praesent vitae suscipit augue. Donec aliquet nec libero nec euismod. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam volutpat orci eget tortor rutrum, eget auctor massa aliquet. Suspendisse placerat metus nec dui vestibulum rutrum. Vivamus tincidunt purus tortor, vitae rhoncus erat commodo ac. Praesent pretium iaculis velit tempor ornare. Duis ornare dignissim tortor. Nulla fringilla quam a velit maximus rutrum. Quisque ipsum est, vestibulum convallis turpis in, bibendum ornare leo.',1),
    ('Test Post2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent feugiat convallis dui at maximus. Praesent quis justo mattis, dignissim arcu a, tincidunt nunc. Maecenas consectetur velit vitae sapien porta lacinia. Suspendisse bibendum metus sed dapibus mattis. Nunc consequat dictum dolor, eu vestibulum lorem. Praesent vitae suscipit augue. Donec aliquet nec libero nec euismod. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam volutpat orci eget tortor rutrum, eget auctor massa aliquet. Suspendisse placerat metus nec dui vestibulum rutrum. Vivamus tincidunt purus tortor, vitae rhoncus erat commodo ac. Praesent pretium iaculis velit tempor ornare. Duis ornare dignissim tortor. Nulla fringilla quam a velit maximus rutrum. Quisque ipsum est, vestibulum convallis turpis in, bibendum ornare leo.',1),
    ('Test Post3', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent feugiat convallis dui at maximus. Praesent quis justo mattis, dignissim arcu a, tincidunt nunc. Maecenas consectetur velit vitae sapien porta lacinia. Suspendisse bibendum metus sed dapibus mattis. Nunc consequat dictum dolor, eu vestibulum lorem. Praesent vitae suscipit augue. Donec aliquet nec libero nec euismod. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam volutpat orci eget tortor rutrum, eget auctor massa aliquet. Suspendisse placerat metus nec dui vestibulum rutrum. Vivamus tincidunt purus tortor, vitae rhoncus erat commodo ac. Praesent pretium iaculis velit tempor ornare. Duis ornare dignissim tortor. Nulla fringilla quam a velit maximus rutrum. Quisque ipsum est, vestibulum convallis turpis in, bibendum ornare leo.',1),
    ('Test Post4', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent feugiat convallis dui at maximus. Praesent quis justo mattis, dignissim arcu a, tincidunt nunc. Maecenas consectetur velit vitae sapien porta lacinia. Suspendisse bibendum metus sed dapibus mattis. Nunc consequat dictum dolor, eu vestibulum lorem. Praesent vitae suscipit augue. Donec aliquet nec libero nec euismod. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam volutpat orci eget tortor rutrum, eget auctor massa aliquet. Suspendisse placerat metus nec dui vestibulum rutrum. Vivamus tincidunt purus tortor, vitae rhoncus erat commodo ac. Praesent pretium iaculis velit tempor ornare. Duis ornare dignissim tortor. Nulla fringilla quam a velit maximus rutrum. Quisque ipsum est, vestibulum convallis turpis in, bibendum ornare leo.',1),
    ('Test Post5', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent feugiat convallis dui at maximus. Praesent quis justo mattis, dignissim arcu a, tincidunt nunc. Maecenas consectetur velit vitae sapien porta lacinia. Suspendisse bibendum metus sed dapibus mattis. Nunc consequat dictum dolor, eu vestibulum lorem. Praesent vitae suscipit augue. Donec aliquet nec libero nec euismod. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam volutpat orci eget tortor rutrum, eget auctor massa aliquet. Suspendisse placerat metus nec dui vestibulum rutrum. Vivamus tincidunt purus tortor, vitae rhoncus erat commodo ac. Praesent pretium iaculis velit tempor ornare. Duis ornare dignissim tortor. Nulla fringilla quam a velit maximus rutrum. Quisque ipsum est, vestibulum convallis turpis in, bibendum ornare leo.',1);